#!/bin/sh
# simple wiki plugin for sws, adds support for [[wikilinks]] and keeps
# track of the backlinks.

add_hook before wiki_init

add_hook during wiki_add_to_index

add_hook after  wiki_insert_backlinks
add_hook after  wiki_create_specials
add_hook after  wiki_clean_up

echo "= wiki plugin loaded"

sws_markup () {
  grep -v -e '^%' "$1" | wikify | "${MARKDOWN-lowdown}"
}

wikify () {
  # Turn [[description|target]] link into relative markdown links or add
  # an absent page marker, and append the target to the backlinks list
  # for further processing.
  awk  -v tmpdir="${links_dir}" -v name="${bare}" '
BEGIN   { code = 0; }
/^```/  { if (code == 0) { code = 1; } else { code = 0; } }
code==1 { print($0); }
code==0 {
  line = $0;
  while (match(line, /`[^`]+`|\[\[([^]]+)\]\]/)) {
    if (substr(line, RSTART, 1) == "`") {
      printf("%s", substr(line, 1, RSTART + RLENGTH - 1));
      line = substr(line, RSTART+RLENGTH);
      continue;
    }
    target = substr(line, RSTART + 2, RLENGTH - 4);
    printf("%s", substr(line, 1, RSTART - 1));
    cpos = RSTART + RLENGTH;
    descr = target;
    if (split(target, parts, /\|/) > 1) {
      descr = parts[1]; target = parts[2];
    }
    if (system("[ -r '"'./${src}/"'" target ".md'"'"' ]") == 0) {
      printf("[%s](./%s.html)", descr, target);
    } else {
      printf("%s^(?)", descr);
    }
    print(name) >> tmpdir "/" target;
    line = substr(line, cpos);
  }
  printf("%s\n", line);
}
END { printf("\n[[BACKLINKS]]\n"); }
'
}

wiki_init () {
  wiki_index="$(mktemp)"
  links_dir="$(mktemp -d)"
}

wiki_add_to_index () {
  printf "%s|%s|%s|%s\n" "$(get_meta "${from}" "D")" \
      "$(basename "$name")" "$(get_meta "${from}" "T")" \
      "${bare}" >> "${wiki_index}"
}

wiki_insert_backlinks () {
  sort "$wiki_index" | while read -r line; do
    bare="$(printf "$line" | cut -d '|' -sf 4)"
    if [ -r "${links_dir}/${bare}" ]; then
      # Turn the list of backlinks into proper links
      sed -i "${links_dir}/${bare}" -e 's|^.*$|<a href="./&.html">&</a>|g'
      # Replace the [[BACKLINKS]] marker with it
      ed -s "${dst}/${bare}.html" <<EOF
g/[[BACKLINKS]]/d\\
i\\
<section id="backlinks">\\
<h2>Backlinks</h2>\\
<p>\\
.\\
.r !cat ${links_dir}/${bare}\\
a\\
</p>\\
</section>
wq
EOF
    else
      # Delete the [[BACKLINKS]] marker
      printf "g/[[BACKLINKS]]/d\nwq\n" | ed -s "${dst}/${bare}.html"
    fi 
  done
}

wiki_create_specials () {
  export page_title="All pages"
  {
    sort -o "${wiki_index}" -t "|" -k 3,4 "${wiki_index}"
    awk -f- -F "|" "${wiki_index}" <<'EOF'
BEGIN { print("<ul>"); }
{
  if (length($3) > 0) { title = $3; } else { title = $4; }
  printf("<li><a href=\"./%s\">%s</a></li>\n", $2, title);
}
END { print("</ul>"); }
EOF
  } | sws_page > "${dst}/all.html"
}

wiki_clean_up () {
  rm -rf "${links_dir}" "${wiki_index}"
}
